CREATE TABLE PRODUCT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150),
    PRICE INTEGER,
    CATEGORY VARCHAR(100)
);

CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(150),
    LAST_NAME VARCHAR(150),
    PASSWORD VARCHAR(100)
);

CREATE TABLE ORDERS (
    ID SERIAL PRIMARY KEY,
    STATUS VARCHAR(100),
    USER_ID INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE ORDER_PRODUCT (
    ID SERIAL PRIMARY KEY,
    ORDER_ID INTEGER,
    PRODUCT_ID INTEGER,
    QUANTITY INTEGER,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);
